<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\Address;
use App\Models\User;

use Illuminate\Support\Facades\Hash;

class DefaultAdminWithAddresses extends Seeder
{

    public static $admin_email = 'kontakt@letscode.it';
    public static $admin_password = "testtest";
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pass = env("DEFAULT_USER_ADMIN_PASSWORD", self::$admin_password);
        if(!empty($pass)) self::$admin_password = $pass;

        $user = User::where('email', self::$admin_email)->first();
        if(!$user)
        {
            $user = User::create([
                'firstname' => 'Default',
                'lastname'  => 'Admin',
                'email'     => self::$admin_email,
                'password'  => Hash::make(self::$admin_password),
            ]);

            echo "Default admin created: $user->email, with password: ". self::$admin_password . PHP_EOL . PHP_EOL;

            $user->attachRole('user');
            $user->attachRole('administrator');
        };

        /**
         * Lista obiektów do dodania jest wprost wzięta z placematik, dlatego zawiera równie niepotrzebne indexy.
         */
        $order = "order";
        $addresses = [
            [
                "uuid" => "f35cf7075ceb61041b8b5b76af74c6ca",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Ostrołęcka",
                "street1" => "Ostrołęcka",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Ostrołęcka",
                "houseNumber" => "12",
                "location" => [
                    "latitude" => 52.761491,
                    "longitude" => 21.59981,
                    "xyClass" => 240,
                ],
                "$order" => 41,
            ],
            [
                "uuid" => "bbe18703218ea0dea66ee5413e6a0b52",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Ostrołęcka",
                "street1" => "Ostrołęcka",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Ostrołęcka",
                "houseNumber" => "4",
                "location" => [
                    "latitude" => 52.761075,
                    "longitude" => 21.59882,
                    "xyClass" => 240,
                ],
                "$order" => 42,
            ],
            [
                "uuid" => "d645b0868cc5ec000029f10893fa9c9b",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Czwórki",
                "street1" => "Czwórki",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Czwórki",
                "houseNumber" => "31",
                "location" => [
                    "latitude" => 52.761285,
                    "longitude" => 21.603684,
                    "xyClass" => 240,
                ],
                "$order" => 43,
            ],
            [
                "uuid" => "07676749692454eb5cdfd1900410a7e9",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Jaśminowa",
                "street1" => "Jaśminowa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Jaśminowa",
                "houseNumber" => "9",
                "location" => [
                    "latitude" => 52.763452,
                    "longitude" => 21.60601,
                    "xyClass" => 240,
                ],
                "$order" => 44,
            ],
            [
                "uuid" => "9aabb6be1466d408c37ab30076ac3f8c",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Poświętne",
                "street1" => "Poświętne",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Poświętne",
                "houseNumber" => "12",
                "location" => [
                    "latitude" => 52.759934,
                    "longitude" => 21.6015,
                    "xyClass" => 240,
                ],
                "$order" => 45,
            ],
            [
                "uuid" => "a952f22eeeecf1e8ade250b55de8d09b",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Grzybowa",
                "street1" => "Grzybowa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Grzybowa",
                "houseNumber" => "5",
                "location" => [
                    "latitude" => 52.759312,
                    "longitude" => 21.605513,
                    "xyClass" => 240,
                ],
                "$order" => 46,
            ],
            [
                "uuid" => "97dd4bfe4aa19e49090247b5e61ffd13",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Jaśminowa",
                "street1" => "Jaśminowa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Jaśminowa",
                "houseNumber" => "1",
                "location" => [
                    "latitude" => 52.762129,
                    "longitude" => 21.604001,
                    "xyClass" => 240,
                ],
                "$order" => 47,
            ],
            [
                "uuid" => "ab3e22cd7098cbc05b869f80edd898e1",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Ostrołęcka",
                "street1" => "Ostrołęcka",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Ostrołęcka",
                "houseNumber" => "44",
                "location" => [
                    "latitude" => 52.76427,
                    "longitude" => 21.604144,
                    "xyClass" => 240,
                ],
                "$order" => 48,
            ],
            [
                "uuid" => "b9854030f3659c9a057960bdff2891e0",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Spokojna",
                "street1" => "Spokojna",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Spokojna",
                "houseNumber" => "3",
                "location" => [
                    "latitude" => 52.75854,
                    "longitude" => 21.599552,
                    "xyClass" => 220,
                ],
                "$order" => 49,
            ],
            [
                "uuid" => "caf64857952d3897f4af6fe51275462e",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Leśna",
                "street1" => "Leśna",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Leśna",
                "houseNumber" => "1A",
                "location" => [
                    "latitude" => 52.757163,
                    "longitude" => 21.585883,
                    "xyClass" => 240,
                ],
                "$order" => 50,
            ],
            [
                "uuid" => "ff3ba111638d8a6455cc9e270b30d7e6",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Strumykowa",
                "street1" => "Strumykowa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Strumykowa",
                "houseNumber" => "8",
                "location" => [
                    "latitude" => 52.76384,
                    "longitude" => 21.605445,
                    "xyClass" => 240,
                ],
                "$order" => 51,
            ],
            [
                "uuid" => "1212fa204174ba0222c64d5fa4123cdd",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Ostrołęcka",
                "street1" => "Ostrołęcka",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Ostrołęcka",
                "houseNumber" => "6",
                "location" => [
                    "latitude" => 52.76117,
                    "longitude" => 21.599003,
                    "xyClass" => 240,
                ],
                "$order" => 52,
            ],
            [
                "uuid" => "90e0f559dcc9e9e12e2f873f6789aefd",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Kasztanowa",
                "street1" => "Kasztanowa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Kasztanowa",
                "houseNumber" => "12",
                "location" => [
                    "latitude" => 52.757634,
                    "longitude" => 21.59187,
                    "xyClass" => 240,
                ],
                "$order" => 53,
            ],
            [
                "uuid" => "b9224385da283492ca8e013ec67d0161",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Kasztanowa",
                "street1" => "Kasztanowa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Kasztanowa",
                "houseNumber" => "1",
                "location" => [
                    "latitude" => 52.757931,
                    "longitude" => 21.593791,
                    "xyClass" => 240,
                ],
                "$order" => 54,
            ],
            [
                "uuid" => "61d6a8672d3986ef1455d51a362fa72f",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Bolesława Chomicza",
                "street1" => "Chomicza",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Bolesława Chomicza",
                "houseNumber" => "4A",
                "location" => [
                    "latitude" => 52.757207,
                    "longitude" => 21.590033,
                    "xyClass" => 230,
                ],
                "$order" => 55,
            ],
            [
                "uuid" => "2d400767fea95fd280cda74fda715495",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Bolesława Chomicza",
                "street1" => "Chomicza",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Bolesława Chomicza",
                "houseNumber" => "4",
                "location" => [
                    "latitude" => 52.757207,
                    "longitude" => 21.590033,
                    "xyClass" => 240,
                ],
                "$order" => 56,
            ],
            [
                "uuid" => "70e2e51c064fe9b25aacb7e4c3fb436e",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "26",
                "location" => [
                    "latitude" => 52.758874,
                    "longitude" => 21.591515,
                    "xyClass" => 240,
                ],
                "$order" => 57,
            ],
            [
                "uuid" => "ee245650c140d04a6eb20fe1fd9e86bc",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "55",
                "location" => [
                    "latitude" => 52.758024,
                    "longitude" => 21.589956,
                    "xyClass" => 240,
                ],
                "$order" => 58,
            ],
            [
                "uuid" => "726dea99691d2e2932715cca1fb6d74c",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "45",
                "location" => [
                    "latitude" => 52.758505,
                    "longitude" => 21.591145,
                    "xyClass" => 240,
                ],
                "$order" => 59,
            ],
            [
                "uuid" => "22f10dbbed0ce9d8c949d8fc6ca868fd",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "43",
                "location" => [
                    "latitude" => 52.758454,
                    "longitude" => 21.591411,
                    "xyClass" => 240,
                ],
                "$order" => 60,
            ],
            [
                "uuid" => "ccc8d7899d78d54eb9e755956afc16fe",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "21",
                "location" => [
                    "latitude" => 52.595927,
                    "longitude" => 21.456552,
                    "xyClass" => 240,
                ],
                "$order" => 181,
            ],
            [
                "uuid" => "cb1ca89ccad37e02ba0f9dc2f327eb1a",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "2",
                "location" => [
                    "latitude" => 52.595294,
                    "longitude" => 21.457629,
                    "xyClass" => 240,
                ],
                "$order" => 182,
            ],
            [
                "uuid" => "0b59c64849f78d5f262efef54d742ff9",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "13",
                "location" => [
                    "latitude" => 52.595648,
                    "longitude" => 21.456643,
                    "xyClass" => 240,
                ],
                "$order" => 183,
            ],
            [
                "uuid" => "3424ee0fb2ffa5caf7ed99e837c26b66",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Bolesława Prusa",
                "street1" => "Prusa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Bolesława Prusa",
                "houseNumber" => "24",
                "location" => [
                    "latitude" => 52.592691,
                    "longitude" => 21.437576,
                    "xyClass" => 215,
                ],
                "$order" => 184,
            ],
            [
                "uuid" => "38d5a778cabb0e2f098126f4fb10be17",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Bolesława Prusa",
                "street1" => "Prusa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Bolesława Prusa",
                "houseNumber" => "45",
                "location" => [
                    "latitude" => 52.59335,
                    "longitude" => 21.437034,
                    "xyClass" => 240,
                ],
                "$order" => 185,
            ],
            [
                "uuid" => "55e0e36744969c82ae329be450080f9d",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Bolesława Prusa",
                "street1" => "Prusa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Bolesława Prusa",
                "houseNumber" => "39",
                "location" => [
                    "latitude" => 52.593183,
                    "longitude" => 21.437028,
                    "xyClass" => 240,
                ],
                "$order" => 186,
            ],
            [
                "uuid" => "d10911ed7c3554e234ddb0c16bc63a77",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Bolesława Prusa",
                "street1" => "Prusa",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Bolesława Prusa",
                "houseNumber" => "34",
                "location" => [
                    "latitude" => 52.593091,
                    "longitude" => 21.437615,
                    "xyClass" => 240,
                ],
                "$order" => 187,
            ],
            [
                "uuid" => "26a7e96e24db3e4b9419f44750c1e1ab",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "59",
                "location" => [
                    "latitude" => 52.598504,
                    "longitude" => 21.456208,
                    "xyClass" => 240,
                ],
                "$order" => 188,
            ],
            [
                "uuid" => "ed4a326a7edf66e4bd428947d8690c3c",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "22",
                "location" => [
                    "latitude" => 52.596323,
                    "longitude" => 21.457035,
                    "xyClass" => 240,
                ],
                "$order" => 189,
            ],
            [
                "uuid" => "4a4e5d9de81b8c01f55b662e95943f54",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "9",
                "location" => [
                    "latitude" => 52.595422,
                    "longitude" => 21.456746,
                    "xyClass" => 240,
                ],
                "$order" => 190,
            ],
            [
                "uuid" => "fcd1a2bc73c1f3901910f425fb88e2f8",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "80",
                "location" => [
                    "latitude" => 52.600345,
                    "longitude" => 21.456433,
                    "xyClass" => 240,
                ],
                "$order" => 191,
            ],
            [
                "uuid" => "44b0982775122f3da581b758e380ec13",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "78",
                "location" => [
                    "latitude" => 52.600178,
                    "longitude" => 21.456439,
                    "xyClass" => 240,
                ],
                "$order" => 192,
            ],
            [
                "uuid" => "2f7713d43b18df371125a491bb76f0c8",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "74",
                "location" => [
                    "latitude" => 52.600019,
                    "longitude" => 21.456489,
                    "xyClass" => 240,
                ],
                "$order" => 193,
            ],
            [
                "uuid" => "3e69e288b7a3727a516c52157b853ef6",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "72",
                "location" => [
                    "latitude" => 52.599957,
                    "longitude" => 21.456509,
                    "xyClass" => 240,
                ],
                "$order" => 194,
            ],
            [
                "uuid" => "08b0faf2fdddfe6e18d2a3e489784e29",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "7",
                "location" => [
                    "latitude" => 52.595349,
                    "longitude" => 21.456807,
                    "xyClass" => 240,
                ],
                "$order" => 195,
            ],
            [
                "uuid" => "62e90cdc2ae7f3b015fddf03833d8453",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "67",
                "location" => [
                    "latitude" => 52.599308,
                    "longitude" => 21.456017,
                    "xyClass" => 240,
                ],
                "$order" => 196,
            ],
            [
                "uuid" => "caa8c88597f3209f2f1a5c8d5a7f750a",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "61A",
                "location" => [
                    "latitude" => 52.598641,
                    "longitude" => 21.456156,
                    "xyClass" => 240,
                ],
                "$order" => 197,
            ],
            [
                "uuid" => "e771c97547091f0f0e7c843a8c02eebe",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "48A",
                "location" => [
                    "latitude" => 52.597632,
                    "longitude" => 21.456849,
                    "xyClass" => 240,
                ],
                "$order" => 198,
            ],
            [
                "uuid" => "f2fa6a70d387b267bd8247acbf607adc",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "47",
                "location" => [
                    "latitude" => 52.597722,
                    "longitude" => 21.456206,
                    "xyClass" => 240,
                ],
                "$order" => 199,
            ],
            [
                "uuid" => "42ed3fc1a524a8c1d62620b7ec5793c5",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Wyszków",
                "city" => "Wyszków",
                "cityDistricted" => "Wyszków",
                "zip" => "07-200",
                "street" => "Świętojańska",
                "street1" => "Świętojańska",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Świętojańska",
                "houseNumber" => "46A",
                "location" => [
                    "latitude" => 52.597442,
                    "longitude" => 21.456889,
                    "xyClass" => 240,
                ],
                "$order" => 200,
            ],
            [
                "uuid" => "70e2e51c064fe9b25aacb7e4c3fb436e",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "26",
                "location" => [
                    "latitude" => 52.758874,
                    "longitude" => 21.591515,
                    "xyClass" => 240,
                ],
                "$order" => 321,
            ],
            [
                "uuid" => "ee245650c140d04a6eb20fe1fd9e86bc",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "55",
                "location" => [
                    "latitude" => 52.758024,
                    "longitude" => 21.589956,
                    "xyClass" => 240,
                ],
                "$order" => 322,
            ],
            [
                "uuid" => "726dea99691d2e2932715cca1fb6d74c",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "45",
                "location" => [
                    "latitude" => 52.758505,
                    "longitude" => 21.591145,
                    "xyClass" => 240,
                ],
                "$order" => 323,
            ],
            [
                "uuid" => "22f10dbbed0ce9d8c949d8fc6ca868fd",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "43",
                "location" => [
                    "latitude" => 52.758454,
                    "longitude" => 21.591411,
                    "xyClass" => 240,
                ],
                "$order" => 324,
            ],
            [
                "uuid" => "ac4d7aa85ec8e31466752d841718adb5",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "14A",
                "location" => [
                    "latitude" => 52.759389,
                    "longitude" => 21.592688,
                    "xyClass" => 240,
                ],
                "$order" => 325,
            ],
            [
                "uuid" => "54056e9ae8539c1aad1848683b9fa767",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "11",
                "location" => [
                    "latitude" => 52.759536,
                    "longitude" => 21.594191,
                    "xyClass" => 240,
                ],
                "$order" => 326,
            ],
            [
                "uuid" => "7eabd079ae4cbf468957accb2c9fb401",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "52",
                "location" => [
                    "latitude" => 52.756631,
                    "longitude" => 21.585129,
                    "xyClass" => 240,
                ],
                "$order" => 327,
            ],
            [
                "uuid" => "6afb60742c9692f5284dad9f454bed2b",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "9",
                "location" => [
                    "latitude" => 52.759574,
                    "longitude" => 21.594303,
                    "xyClass" => 240,
                ],
                "$order" => 328,
            ],
            [
                "uuid" => "1ea7985dcf36423afbd2c4522a6b926f",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "40",
                "location" => [
                    "latitude" => 52.757702,
                    "longitude" => 21.588134,
                    "xyClass" => 240,
                ],
                "$order" => 329,
            ],
            [
                "uuid" => "5d571692b66867cbdf38c8d2bef299a1",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "20",
                "location" => [
                    "latitude" => 52.759451,
                    "longitude" => 21.59291,
                    "xyClass" => 240,
                ],
                "$order" => 330,
            ],
            [
                "uuid" => "ba080c3fcd60586e243780e3b9acd0c7",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "17",
                "location" => [
                    "latitude" => 52.759283,
                    "longitude" => 21.593604,
                    "xyClass" => 240,
                ],
                "$order" => 331,
            ],
            [
                "uuid" => "c5b0129c8babbb9503a82469dc659689",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "16",
                "location" => [
                    "latitude" => 52.759531,
                    "longitude" => 21.593375,
                    "xyClass" => 240,
                ],
                "$order" => 332,
            ],
            [
                "uuid" => "b09335e2c31240c2213259fb3ed91235",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "16A",
                "location" => [
                    "latitude" => 52.758916,
                    "longitude" => 21.59149,
                    "xyClass" => 240,
                ],
                "$order" => 333,
            ],
            [
                "uuid" => "d7bbad29d363314056d69664b397c985",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "19B",
                "location" => [
                    "latitude" => 52.759238,
                    "longitude" => 21.593359,
                    "xyClass" => 240,
                ],
                "$order" => 334,
            ],
            [
                "uuid" => "89669710555e2329e8929d85f70f0229",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "6",
                "location" => [
                    "latitude" => 52.759985,
                    "longitude" => 21.594546,
                    "xyClass" => 240,
                ],
                "$order" => 335,
            ],
            [
                "uuid" => "cbc9bc284d1b37b75b1652084fbbee1d",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "49",
                "location" => [
                    "latitude" => 52.758307,
                    "longitude" => 21.590578,
                    "xyClass" => 240,
                ],
                "$order" => 336,
            ],
            [
                "uuid" => "1f2d416046b91499d842706e3afb3574",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "34",
                "location" => [
                    "latitude" => 52.758562,
                    "longitude" => 21.590418,
                    "xyClass" => 240,
                ],
                "$order" => 337,
            ],
            [
                "uuid" => "9e6fc40b04891dbfbd736f37b4353da4",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "31",
                "location" => [
                    "latitude" => 52.758838,
                    "longitude" => 21.592266,
                    "xyClass" => 240,
                ],
                "$order" => 338,
            ],
            [
                "uuid" => "eadf7378e5b16f0853c8ac683159a938",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "28",
                "location" => [
                    "latitude" => 52.758798,
                    "longitude" => 21.591273,
                    "xyClass" => 240,
                ],
                "$order" => 339,
            ],
            [
                "uuid" => "1890c32e79b172047ca7bc0046f6e5d8",
                "state" => "mazowieckie",
                "county" => "wyszkowski",
                "municipality" => "Długosiodło",
                "city" => "Długosiodło",
                "cityDistricted" => "Długosiodło",
                "zip" => "07-210",
                "street" => "Królowej Jadwigi",
                "street1" => "Królowej Jadwigi",
                "streetPrefix" => "ul.",
                "streetTeryt" => "Królowej Jadwigi",
                "houseNumber" => "14",
                "location" => [
                    "latitude" => 52.759719,
                    "longitude" => 21.59357,
                    "xyClass" => 240,
                ],
                "$order" => 340,
            ],
        ];

        foreach($addresses as $address )
        {
            $model = new Address();
            $model->city = $address['city'];
            $model->cityDistricted = $address['cityDistricted'];
            $model->county = $address['county'];
            $model->houseNumber = $address['houseNumber'];
            $model->municipality = $address['municipality'];
            
            //$model->name = $address['name'];
            $model->name = $address['city'] . ', ' . $address['street'] . ' ' . $address['houseNumber'];

            $model->state = $address['state'];
            $model->street = $address['street'];
            $model->street1 = $address['street1'];
            $model->streetPrefix = $address['streetPrefix'];
            $model->streetTeryt = $address['streetTeryt'];
            $model->uuid = $address['uuid'];
            $model->zip = $address['zip'];

            $model->location_latitude = $address['location']['latitude'];
            $model->location_longitude = $address['location']['longitude'];
            $model->location_xyClass = $address['location']['xyClass'];

            $model->user_id = $user->id;

            $model->save();

            echo "Adding address: " . $model->name . PHP_EOL; 
        }

        var_dump("Addresses in seeder:");
        var_dump(count($addresses));


    }
}
